# Generated by Django 3.0.7 on 2020-06-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0002_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=8),
        ),
        migrations.AddField(
            model_name='bug',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
