# Generated by Django 3.0.7 on 2020-06-18 02:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0004_projectusers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectusers',
            options={'verbose_name_plural': 'Project Users'},
        ),
        migrations.AlterUniqueTogether(
            name='projectusers',
            unique_together={('project', 'user')},
        ),
    ]
